//
export const LOAD_PRODUCTS_INIT = 'LOAD_PRODUCTS_INIT';
export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';
export const LOAD_PRODUCTS_ERROR = 'LOAD_PRODUCTS_ERROR';

export const LOAD_MORE_PRODUCTS_INIT = 'LOAD_MORE_PRODUCTS_INIT';
export const LOAD_MORE_PRODUCTS_SUCCESS = 'LOAD_MORE_PRODUCTS_SUCCESS';
export const LOAD_MORE_PRODUCTS_ERROR = 'LOAD_MORE_PRODUCTS_ERROR';

export const SET_FILTER_BY = 'SET_FILTER_BY';
export const SET_SORT_BY = 'SET_SORT_BY';
export const SET_PAGE_TO_LOAD = 'SET_PAGE_TO_LOAD';

export const LIKE_PRODUCT = 'LIKE_PRODUCT';
export const UNLIKE_PRODUCT = 'UNLIKE_PRODUCT';
export const LOAD_LIKED_PRODUCTS = 'LOAD_LIKED_PRODUCTS';
